### PR TITLE
deny unused_mut and unused_variables

### PR DESCRIPTION
**Pull request by MaxVerevkin**

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thanks!

**Comment by Andlon** [comment]
I'm a bit late since this was already merged, but for lints like these, wouldn't it generally be better to deny warnings on CI than denying them outright? Often when developing I temporarily have many unused variables or similar, and it seems very annoying if this leads to intermediate compilation failures... Not a big deal since you can of course temporarily remove the `deny`, I don't know :shrug:

**Comment by MaxVerevkin** [comment]
Maybe we can allow them in debug builds and deny in release? I'll check it it's possible.

**Comment by Ralith** [comment]
+1 to making this sort of thing CI-only; applying strict linting to WIP code doesn't make a lot of sense.

**Pull request merged**
