### PR TITLE
Clippy fixing

### PR DESCRIPTION
**Pull request by OfficialURL**
I'll be trying to decrease the number of clippy warnings (with the end goal of closing #913.) I'll fix a few at a time to make sure I don't introduce any bugs, and I'll start with those that aren't breaking changes.

### CODE REVIEW

**Comment by OfficialURL** [comment]
I've got no idea what happened in Checkpoint 3. Apparently `nalgebra` didn't like it when I took out those... clones? Surely that shouldn't be having a noticeable effect.

**Comment by OfficialURL** [comment]
Should I revert the changes I did where I replaced clones by dereferences? I don't see how these could be inequivalent, but since these were in a macro, I guess anything goes.

**Comment by sebcrozet** [comment]
Thank you for this PR! Regarding the `clone` issue: I think the problem comes from the [trait-bound on the implementation](https://github.com/dimforge/nalgebra/blob/dev/src/geometry/translation.rs#L41) of `Copy` for `Translation`:
```rust
impl<T: Scalar + Copy, const D: usize> Copy for Translation<T, D> where Owned<T, Const<D>>: Copy {}
```

That `Owned<T, Const<D>>: Copy` should always be satisfied, but for some reasons the compiler fails to see it in some context. Just removing that trait bound (which is actually no longer necessary, this is just a remain from before the switch to const-generics):
```rust
impl<T: Scalar + Copy, const D: usize> Copy for Translation<T, D> {}
```
will allow you to get rid of the `.clone()`.

**Comment by OfficialURL** [comment]
I'm having some trouble with `test-nalgebra` specifically. I must've accidentally reverted something important. How can I check this on my side? Running `cargo test --features debug,compare,rand,macros` doesn't give me any errors.

**Comment by OfficialURL** [comment]
This PR will fix all clippy warnings, save for those that would be fixed by PR #918, and those that would close Issue #791 (the `#Safety` sections).

**Comment by sebcrozet** [comment]
This is great, thank you!

**Pull request merged**
