### PR TITLE
Remove `Dim::is()` function because it may be used in unsound ways

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Very similar to #957. This part of `nalgebra` will cause UB for a poorly implemented `Dim`:  https://github.com/dimforge/nalgebra/blob/7f236d88aab0c8310d759720c2d8b13bee8e5aeb/src/base/blas.rs#L48-L57

By the way, I think it should be fine to remove those lines. Thanks to monomorphisation, this function will (probably) get optimized anyway https://github.com/dimforge/nalgebra/blob/7f236d88aab0c8310d759720c2d8b13bee8e5aeb/src/base/matrix_slice.rs#L170-L175

### CODE REVIEW

**Comment by Ralith** [comment]
Alternatively, `Dim` could be made an unsafe trait.

**Comment by Andlon** [comment]
> Alternatively, `Dim` could be made an unsafe trait.

I'd prefer this solution as removing it might unnecessarily break user code (iirc I also specialize for dimensions in some places). Besides, `D::is::<U2>()` has much nicer syntax than e.g. `TypeId::of::<D>() == TypeId::of::<U2>()`.

**Comment by MaxVerevkin** [comment]
Okay, so instead of removing this function, I've created a new unsafe trait which is implemented for all `'static`types. I think it makes more sense because now it can be used with any type.

**Comment by Ralith** [comment]
Wouldn't that still break the same user code?

**Comment by sebcrozet** [comment]
I think it’s best to just make the `Dim` trait unsafe here. It sounds reasonable that unsafe code reading matrix dimensions should be able to rely on any of the `Dim` functions (like `Dim::value()`) to behave properly.

> By the way, I think it should be fine to remove those lines. Thanks to monomorphisation, this function will (probably) get optimized anyway

This needs to be benchmarked. It’s my experience that the compiler’s optimizer is annoyingly picky about what’s in the `blas` module, so it is not certain that the monomorphised code will really be optimized properly.

**Comment by MaxVerevkin** [comment]
> This needs to be benchmarked

Well, I'm not sure how to do it, so I'll leave it as it is for now.

**Pull request closed without merging**
