### PR TITLE
Remove abomonation support

### PR DESCRIPTION
**Pull request by saethlin**
Abomonation has numerous soundness problems which have been well-documented in its issue tracker for over 2 years. Some of them could be fixed, but some are fundamental to its design. If a user wants super-fast ser/de, they should use rkyv. See https://rustsec.org/advisories/RUSTSEC-2021-0120.html.

Closes https://github.com/dimforge/nalgebra/issues/1011

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thanks! I think this is the right move.
Unfortunately the CI doesn’t want to run of this PR (likely because the workflow has been modified), but I’m confident that the changes are straightforward enough not to cause any issue.

**Comment by saethlin** [comment]
> likely because the workflow has been modified

Have you seen this happen before? Most of my experience is with Travis, which occasionally just seems to miss a commit. I'm going to push an empty commit here and see if that causes the CI to wake up.

**Comment by saethlin** [comment]
Ah-ha! Now I see "1 workflow awaiting approval"

**Comment by sebcrozet** [comment]
> Have you seen this happen before?

I thought I saw this before, but I may be misremembering. Looks like your additional commit did the trick, thanks!

**Pull request merged**
