### PR TITLE
Take-2 of polar-decomposition

### PR DESCRIPTION
**Pull request by metric-space**
Code inspired by this PR/thread: https://github.com/dimforge/nalgebra/pull/656

Main person behind this is @LucasCampos

This PR  implements  [matrix polar decomposition](https://en.wikipedia.org/wiki/Polar_decomposition)

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thanks! I took the liberty of making a few small changes:
- I renamed `Matrix::polar` to `Matrix::try_polar` and added `Matrix::polar` which returns the result instead of `Option` (similar to the other methods, e.g., `Matrix::svd` and `Matrix::try_svd`).
- I made your test use `proptest`  instead of `DMatrix::new_random`. This will cover more cases.

The new proptest test is failing right now. I haven’t investigated in details yet to determine if this is a bug, or if the test are just failing because we used an epsilon that is too restrictive.

**Comment by metric-space** [comment]
@sebcrozet Thank you for the review and the additions. Not sure if you plan to look into it further but I will take look into the bug with the prop test and return back with a fix/solution

**Comment by metric-space** [comment]
I zeroed in on the causes. 

1. The orthogonal test is a proxy for a unitary/semi-unitary check. It's a unitary check for square matrices and supposed to be a semi-unitary check for rectangular matrices which is a bit more involved because it tests whether either the rows are orthogonal or the columns are orthogonal. It depends on the dimensions of the rectangular matrix

2. In the main test, the test svd  generated  is ordered while the method based `polar` calls the unordered SVD for further processing, which gives different decompositions

Fixes applied 
Ball's back in your court @sebcrozet

**Comment by sebcrozet** [comment]
Perfect, thanks!

**Comment by metric-space** [comment]
Thank you

**Pull request merged**
