### PR TITLE
Add partial `rkyv` support

### PR DESCRIPTION
**Pull request by djkoloski**
This should get nalgebra support started off. It's still missing support for all types as well as tests, but it does have distributive archived types so no logic needs to get rewritten.

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thank you for this PR! A have a few commits ready to make the CI pass, but it looks like you didn't check the PR option that lets me push to your branch directly. Would it be ok for you to [check the related box](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)?

**Comment by djkoloski** [comment]
Whoops, I was also working on getting this passing. Would the new patch I pushed be okay?

**Comment by sebcrozet** [comment]
Oh, thanks! Your patch is fine :+1: 
Would you mind rebasing this on `dev` too in order to get rid of the conflict?

**Comment by djkoloski** [comment]
Okay I think I did it right!

**Comment by sebcrozet** [comment]
All good, thanks!

**Pull request merged**
