### PR TITLE
Update syn to `2.0`

### PR DESCRIPTION
**Pull request by yotamofek**
Requires no adaptations.

### CODE REVIEW

**Comment by CAD97** [comment]
Cargo didn't find `ahash@0.7.7` for some reason. Seems spurious and unrelated to the syn update.

**Comment by yotamofek** [comment]
Ah great, now it failed due to a different spurious and unrelated problem 😅
Let's run CI again..

**Comment by djc** [comment]
Friendly ping? Would be nice to get this merged (and ideally, released) to reduce compile-times for downstream projects?

**Comment by Andlon** [comment]
> Friendly ping? Would be nice to get this merged (and ideally, released) to reduce compile-times for downstream projects.

I agree. However, if I run `cargo tree -p nalgebra --all-features`, there are a few (opt-in) dependencies that still seem to rely on `syn 1.0`. Having both `syn 1.0` and `syn 2.0` in the dependency tree seems strictly worse. Perhaps we can upgrade these too though. It's not clear to me how much effort is required, as I suspect some packages might simply not have been updated to support `syn 2.0`.

**Comment by Andlon** [comment]
Actually, I realized that I hadn't updated dependencies in my dev environment for a while. After running `cargo update`, I see that the only other dependency that has not been updated to use `syn 2.0` is `rkyv`. Since we *anyway* might have both `syn 1.0` and `syn 2.0` in the tree at this point due to `serde` using `2.0`, I think we should go ahead and merge this as-is, and then log an issue for `rkyv` to also upgrade its `syn` version to `2.0`.

**Comment by djc** [comment]
> However, as far as I can tell, we don't actually need a new `nalgebra` release for this. If we release `nalgebra-macros` with a new patch version, then existing `nalgebra` users should get the change through `cargo update`.

Yes, that sounds correct. I think that means you don't even need to change nalgebra to bump the nalgebra-macros dependency.

**Comment by bash** [comment]
Resolves #1403 (I forgot to check PRs before opening an issue ^^)

**Comment by sebcrozet** [comment]
Thank you all for making/reviewing this PR!

**Pull request merged**
