### PR TITLE
Make "Point::new" a const fn

### PR DESCRIPTION
**Pull request by SolraBizna**
Based on my brief testing, these two changed lines are all that is needed to make this work.

### CODE REVIEW

**Comment by Ralith** [comment]
We should probably do this for more than just the 1D case.

**Comment by SolraBizna** [comment]
My change works for every case that a `Point::new` is generated for, not just 1D. (GitHub's diff makes this hard to tell.)

**Comment by Ralith** [comment]
Right you are.

**Review by Ralith — APPROVED** [review]

**Comment by necauqua** [comment]
Hi!
Any movement on this?
Seems like an extremely simple improvement

**Comment by sebcrozet** [comment]
Thanks!

**Pull request merged**
